### ISSUE TITLE
Add timestamp format requirement to documentation.

### ISSUE THREAD

**Issue by brylie** [gyaikhom/activitymap#1]
I have an array of objects containing a field for time. The time field contains a date object, but the calendar does not seem to render correctly. How should this date object be formatted to get the calendar to render?

**Comment by brylie** [comment]
I have tried converting the Date objects to unix timestamps with Date.getTime(), as well as parsing the result to integer. This is really unclear what the plugin expects, and all I have to go by is the example CSV.

**Comment by brylie** [comment]
The sourcecode simply states [timestamp](https://github.com/gyaikhom/activitymap/blob/master/activitymap.js#L7), but does not specify a format (such as seconds or miliseconds).

**Comment by brylie** [comment]
OK, I figured out that the `Date.getTime()` was sufficient to get the timestamp in the correct format. Please add this to the documentation :-)

**Comment by gyaikhom** [comment]
I have just added a facility to allow specifying time as JavaScript Date() object. I have also updated the documentation. Thanks for suggesting the improvements.
