### ISSUE TITLE
Highest value is not rendering background-color

### ISSUE THREAD

**Issue by brylie** [gyaikhom/activitymap#2]
When generating the chart of months, the day with the highest value does not have a background-color. All other days have background color.

**Comment by gyaikhom** [comment]
Unable to replicate. Could you please supply sample data causing the issue?

**Comment by brylie** [comment]
Here is an example:

``` javascript
var data = [
  {
    timestamp: new Date("Sat Aug 15 2015 00:00:00 GMT+0300 (EEST)").getTime(),
    number: 10
  },
  {
    timestamp: new Date("Sat Aug 22 2015 00:00:00 GMT+0300 (EEST)").getTime(),
    number: 20
  },
  {
    timestamp: new Date("Sat Aug 29 2015 00:00:00 GMT+0300 (EEST)").getTime(),
    number: 30
  },
];
```

**Comment by gyaikhom** [comment]
Thanks Brylie. You identified a critical bug in the colour assignment. I have made the necessary changes. Could you please confirm if the issue is fixed?

**Comment by brylie** [comment]
I have tested the 1.2 release, and the highest color value works now :-)
