### ISSUE TITLE
How to specify initial height of calendar to match data size?

### ISSUE THREAD

**Issue by brylie** [gyaikhom/activitymap#3]
When the calendar initially renders, it is approximately 10px tall. How can I tell the calendar to render tall enough to fit the entire data set? Right now I have this hard-coded to 33ems, so that it fits around one year in the calendar view.

**Comment by gyaikhom** [comment]
Version 1.1.1 allows the activity map to expand. See index.html for example.

**Comment by brylie** [comment]
Is the necessary parameter `fit: true`?
