### ISSUE TITLE
Display one year as continuous strip?

### ISSUE THREAD

**Issue by brylie** [gyaikhom/activitymap#4]
Is it possible to display the activity heatmap in a continuous band, showing around one year of activity? I.e. this is how Github displays commit activity on a user profile.

**Comment by gyaikhom** [comment]
I haven't implemented it, but should be possible.

**Comment by gyaikhom** [comment]
`Version 1.2` implements compact mode which allows display of entire year in one band. Please see`README.md` and `index.html` for details. Kindly advise me if there are issues.

**Comment by brylie** [comment]
Really great work! Are you on Gratipay or some similar site?

**Comment by gyaikhom** [comment]
Pleased to know that the project was useful. I am on Gratipay: gyaikhom@github.com.
